/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class application_Graph */

#ifndef _Included_application_Graph
#define _Included_application_Graph
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     application_Graph
 * Method:    calculate
 * Signature: ([[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_application_Graph_calculate
  (JNIEnv *, jobject, jobjectArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
